// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dota_usercmd.proto
// Protobuf Java Version: 4.28.0

package kz.moltenhaze.proto.dota;

public final class DotaUsercmd {
  private DotaUsercmd() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "",
      DotaUsercmd.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CDota2UserCmdPBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CDota2UserCmdPB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .CBaseUserCmdPB base = 1;</code>
     * @return Whether the base field is set.
     */
    boolean hasBase();
    /**
     * <code>optional .CBaseUserCmdPB base = 1;</code>
     * @return The base.
     */
    kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPB getBase();
    /**
     * <code>optional .CBaseUserCmdPB base = 1;</code>
     */
    kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPBOrBuilder getBaseOrBuilder();

    /**
     * <code>optional int32 spectator_query_unit_entindex = 2;</code>
     * @return Whether the spectatorQueryUnitEntindex field is set.
     */
    boolean hasSpectatorQueryUnitEntindex();
    /**
     * <code>optional int32 spectator_query_unit_entindex = 2;</code>
     * @return The spectatorQueryUnitEntindex.
     */
    int getSpectatorQueryUnitEntindex();

    /**
     * <code>optional .CMsgVector crosshairtrace = 3;</code>
     * @return Whether the crosshairtrace field is set.
     */
    boolean hasCrosshairtrace();
    /**
     * <code>optional .CMsgVector crosshairtrace = 3;</code>
     * @return The crosshairtrace.
     */
    kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVector getCrosshairtrace();
    /**
     * <code>optional .CMsgVector crosshairtrace = 3;</code>
     */
    kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVectorOrBuilder getCrosshairtraceOrBuilder();

    /**
     * <code>optional int32 cameraposition_x = 4;</code>
     * @return Whether the camerapositionX field is set.
     */
    boolean hasCamerapositionX();
    /**
     * <code>optional int32 cameraposition_x = 4;</code>
     * @return The camerapositionX.
     */
    int getCamerapositionX();

    /**
     * <code>optional int32 cameraposition_y = 5;</code>
     * @return Whether the camerapositionY field is set.
     */
    boolean hasCamerapositionY();
    /**
     * <code>optional int32 cameraposition_y = 5;</code>
     * @return The camerapositionY.
     */
    int getCamerapositionY();

    /**
     * <code>optional uint32 clickbehavior = 6;</code>
     * @return Whether the clickbehavior field is set.
     */
    boolean hasClickbehavior();
    /**
     * <code>optional uint32 clickbehavior = 6;</code>
     * @return The clickbehavior.
     */
    int getClickbehavior();

    /**
     * <code>optional uint32 statspanel = 7;</code>
     * @return Whether the statspanel field is set.
     */
    boolean hasStatspanel();
    /**
     * <code>optional uint32 statspanel = 7;</code>
     * @return The statspanel.
     */
    int getStatspanel();

    /**
     * <code>optional uint32 shoppanel = 8;</code>
     * @return Whether the shoppanel field is set.
     */
    boolean hasShoppanel();
    /**
     * <code>optional uint32 shoppanel = 8;</code>
     * @return The shoppanel.
     */
    int getShoppanel();

    /**
     * <code>optional uint32 stats_dropdown = 9;</code>
     * @return Whether the statsDropdown field is set.
     */
    boolean hasStatsDropdown();
    /**
     * <code>optional uint32 stats_dropdown = 9;</code>
     * @return The statsDropdown.
     */
    int getStatsDropdown();

    /**
     * <code>optional uint32 stats_dropdown_sort = 10;</code>
     * @return Whether the statsDropdownSort field is set.
     */
    boolean hasStatsDropdownSort();
    /**
     * <code>optional uint32 stats_dropdown_sort = 10;</code>
     * @return The statsDropdownSort.
     */
    int getStatsDropdownSort();
  }
  /**
   * Protobuf type {@code CDota2UserCmdPB}
   */
  public static final class CDota2UserCmdPB extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CDota2UserCmdPB)
      CDota2UserCmdPBOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 0,
        /* suffix= */ "",
        CDota2UserCmdPB.class.getName());
    }
    // Use CDota2UserCmdPB.newBuilder() to construct.
    private CDota2UserCmdPB(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CDota2UserCmdPB() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kz.moltenhaze.proto.dota.DotaUsercmd.internal_static_CDota2UserCmdPB_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kz.moltenhaze.proto.dota.DotaUsercmd.internal_static_CDota2UserCmdPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB.class, kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB.Builder.class);
    }

    private int bitField0_;
    public static final int BASE_FIELD_NUMBER = 1;
    private kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPB base_;
    /**
     * <code>optional .CBaseUserCmdPB base = 1;</code>
     * @return Whether the base field is set.
     */
    @java.lang.Override
    public boolean hasBase() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .CBaseUserCmdPB base = 1;</code>
     * @return The base.
     */
    @java.lang.Override
    public kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPB getBase() {
      return base_ == null ? kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPB.getDefaultInstance() : base_;
    }
    /**
     * <code>optional .CBaseUserCmdPB base = 1;</code>
     */
    @java.lang.Override
    public kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPBOrBuilder getBaseOrBuilder() {
      return base_ == null ? kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPB.getDefaultInstance() : base_;
    }

    public static final int SPECTATOR_QUERY_UNIT_ENTINDEX_FIELD_NUMBER = 2;
    private int spectatorQueryUnitEntindex_ = 0;
    /**
     * <code>optional int32 spectator_query_unit_entindex = 2;</code>
     * @return Whether the spectatorQueryUnitEntindex field is set.
     */
    @java.lang.Override
    public boolean hasSpectatorQueryUnitEntindex() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 spectator_query_unit_entindex = 2;</code>
     * @return The spectatorQueryUnitEntindex.
     */
    @java.lang.Override
    public int getSpectatorQueryUnitEntindex() {
      return spectatorQueryUnitEntindex_;
    }

    public static final int CROSSHAIRTRACE_FIELD_NUMBER = 3;
    private kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVector crosshairtrace_;
    /**
     * <code>optional .CMsgVector crosshairtrace = 3;</code>
     * @return Whether the crosshairtrace field is set.
     */
    @java.lang.Override
    public boolean hasCrosshairtrace() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .CMsgVector crosshairtrace = 3;</code>
     * @return The crosshairtrace.
     */
    @java.lang.Override
    public kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVector getCrosshairtrace() {
      return crosshairtrace_ == null ? kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVector.getDefaultInstance() : crosshairtrace_;
    }
    /**
     * <code>optional .CMsgVector crosshairtrace = 3;</code>
     */
    @java.lang.Override
    public kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVectorOrBuilder getCrosshairtraceOrBuilder() {
      return crosshairtrace_ == null ? kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVector.getDefaultInstance() : crosshairtrace_;
    }

    public static final int CAMERAPOSITION_X_FIELD_NUMBER = 4;
    private int camerapositionX_ = 0;
    /**
     * <code>optional int32 cameraposition_x = 4;</code>
     * @return Whether the camerapositionX field is set.
     */
    @java.lang.Override
    public boolean hasCamerapositionX() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 cameraposition_x = 4;</code>
     * @return The camerapositionX.
     */
    @java.lang.Override
    public int getCamerapositionX() {
      return camerapositionX_;
    }

    public static final int CAMERAPOSITION_Y_FIELD_NUMBER = 5;
    private int camerapositionY_ = 0;
    /**
     * <code>optional int32 cameraposition_y = 5;</code>
     * @return Whether the camerapositionY field is set.
     */
    @java.lang.Override
    public boolean hasCamerapositionY() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 cameraposition_y = 5;</code>
     * @return The camerapositionY.
     */
    @java.lang.Override
    public int getCamerapositionY() {
      return camerapositionY_;
    }

    public static final int CLICKBEHAVIOR_FIELD_NUMBER = 6;
    private int clickbehavior_ = 0;
    /**
     * <code>optional uint32 clickbehavior = 6;</code>
     * @return Whether the clickbehavior field is set.
     */
    @java.lang.Override
    public boolean hasClickbehavior() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional uint32 clickbehavior = 6;</code>
     * @return The clickbehavior.
     */
    @java.lang.Override
    public int getClickbehavior() {
      return clickbehavior_;
    }

    public static final int STATSPANEL_FIELD_NUMBER = 7;
    private int statspanel_ = 0;
    /**
     * <code>optional uint32 statspanel = 7;</code>
     * @return Whether the statspanel field is set.
     */
    @java.lang.Override
    public boolean hasStatspanel() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional uint32 statspanel = 7;</code>
     * @return The statspanel.
     */
    @java.lang.Override
    public int getStatspanel() {
      return statspanel_;
    }

    public static final int SHOPPANEL_FIELD_NUMBER = 8;
    private int shoppanel_ = 0;
    /**
     * <code>optional uint32 shoppanel = 8;</code>
     * @return Whether the shoppanel field is set.
     */
    @java.lang.Override
    public boolean hasShoppanel() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional uint32 shoppanel = 8;</code>
     * @return The shoppanel.
     */
    @java.lang.Override
    public int getShoppanel() {
      return shoppanel_;
    }

    public static final int STATS_DROPDOWN_FIELD_NUMBER = 9;
    private int statsDropdown_ = 0;
    /**
     * <code>optional uint32 stats_dropdown = 9;</code>
     * @return Whether the statsDropdown field is set.
     */
    @java.lang.Override
    public boolean hasStatsDropdown() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional uint32 stats_dropdown = 9;</code>
     * @return The statsDropdown.
     */
    @java.lang.Override
    public int getStatsDropdown() {
      return statsDropdown_;
    }

    public static final int STATS_DROPDOWN_SORT_FIELD_NUMBER = 10;
    private int statsDropdownSort_ = 0;
    /**
     * <code>optional uint32 stats_dropdown_sort = 10;</code>
     * @return Whether the statsDropdownSort field is set.
     */
    @java.lang.Override
    public boolean hasStatsDropdownSort() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional uint32 stats_dropdown_sort = 10;</code>
     * @return The statsDropdownSort.
     */
    @java.lang.Override
    public int getStatsDropdownSort() {
      return statsDropdownSort_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getBase());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, spectatorQueryUnitEntindex_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getCrosshairtrace());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, camerapositionX_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, camerapositionY_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeUInt32(6, clickbehavior_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeUInt32(7, statspanel_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeUInt32(8, shoppanel_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        output.writeUInt32(9, statsDropdown_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        output.writeUInt32(10, statsDropdownSort_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBase());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, spectatorQueryUnitEntindex_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getCrosshairtrace());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, camerapositionX_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, camerapositionY_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, clickbehavior_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, statspanel_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, shoppanel_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, statsDropdown_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(10, statsDropdownSort_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB)) {
        return super.equals(obj);
      }
      kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB other = (kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB) obj;

      if (hasBase() != other.hasBase()) return false;
      if (hasBase()) {
        if (!getBase()
            .equals(other.getBase())) return false;
      }
      if (hasSpectatorQueryUnitEntindex() != other.hasSpectatorQueryUnitEntindex()) return false;
      if (hasSpectatorQueryUnitEntindex()) {
        if (getSpectatorQueryUnitEntindex()
            != other.getSpectatorQueryUnitEntindex()) return false;
      }
      if (hasCrosshairtrace() != other.hasCrosshairtrace()) return false;
      if (hasCrosshairtrace()) {
        if (!getCrosshairtrace()
            .equals(other.getCrosshairtrace())) return false;
      }
      if (hasCamerapositionX() != other.hasCamerapositionX()) return false;
      if (hasCamerapositionX()) {
        if (getCamerapositionX()
            != other.getCamerapositionX()) return false;
      }
      if (hasCamerapositionY() != other.hasCamerapositionY()) return false;
      if (hasCamerapositionY()) {
        if (getCamerapositionY()
            != other.getCamerapositionY()) return false;
      }
      if (hasClickbehavior() != other.hasClickbehavior()) return false;
      if (hasClickbehavior()) {
        if (getClickbehavior()
            != other.getClickbehavior()) return false;
      }
      if (hasStatspanel() != other.hasStatspanel()) return false;
      if (hasStatspanel()) {
        if (getStatspanel()
            != other.getStatspanel()) return false;
      }
      if (hasShoppanel() != other.hasShoppanel()) return false;
      if (hasShoppanel()) {
        if (getShoppanel()
            != other.getShoppanel()) return false;
      }
      if (hasStatsDropdown() != other.hasStatsDropdown()) return false;
      if (hasStatsDropdown()) {
        if (getStatsDropdown()
            != other.getStatsDropdown()) return false;
      }
      if (hasStatsDropdownSort() != other.hasStatsDropdownSort()) return false;
      if (hasStatsDropdownSort()) {
        if (getStatsDropdownSort()
            != other.getStatsDropdownSort()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBase()) {
        hash = (37 * hash) + BASE_FIELD_NUMBER;
        hash = (53 * hash) + getBase().hashCode();
      }
      if (hasSpectatorQueryUnitEntindex()) {
        hash = (37 * hash) + SPECTATOR_QUERY_UNIT_ENTINDEX_FIELD_NUMBER;
        hash = (53 * hash) + getSpectatorQueryUnitEntindex();
      }
      if (hasCrosshairtrace()) {
        hash = (37 * hash) + CROSSHAIRTRACE_FIELD_NUMBER;
        hash = (53 * hash) + getCrosshairtrace().hashCode();
      }
      if (hasCamerapositionX()) {
        hash = (37 * hash) + CAMERAPOSITION_X_FIELD_NUMBER;
        hash = (53 * hash) + getCamerapositionX();
      }
      if (hasCamerapositionY()) {
        hash = (37 * hash) + CAMERAPOSITION_Y_FIELD_NUMBER;
        hash = (53 * hash) + getCamerapositionY();
      }
      if (hasClickbehavior()) {
        hash = (37 * hash) + CLICKBEHAVIOR_FIELD_NUMBER;
        hash = (53 * hash) + getClickbehavior();
      }
      if (hasStatspanel()) {
        hash = (37 * hash) + STATSPANEL_FIELD_NUMBER;
        hash = (53 * hash) + getStatspanel();
      }
      if (hasShoppanel()) {
        hash = (37 * hash) + SHOPPANEL_FIELD_NUMBER;
        hash = (53 * hash) + getShoppanel();
      }
      if (hasStatsDropdown()) {
        hash = (37 * hash) + STATS_DROPDOWN_FIELD_NUMBER;
        hash = (53 * hash) + getStatsDropdown();
      }
      if (hasStatsDropdownSort()) {
        hash = (37 * hash) + STATS_DROPDOWN_SORT_FIELD_NUMBER;
        hash = (53 * hash) + getStatsDropdownSort();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CDota2UserCmdPB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CDota2UserCmdPB)
        kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kz.moltenhaze.proto.dota.DotaUsercmd.internal_static_CDota2UserCmdPB_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kz.moltenhaze.proto.dota.DotaUsercmd.internal_static_CDota2UserCmdPB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB.class, kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB.Builder.class);
      }

      // Construct using kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getBaseFieldBuilder();
          getCrosshairtraceFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        base_ = null;
        if (baseBuilder_ != null) {
          baseBuilder_.dispose();
          baseBuilder_ = null;
        }
        spectatorQueryUnitEntindex_ = 0;
        crosshairtrace_ = null;
        if (crosshairtraceBuilder_ != null) {
          crosshairtraceBuilder_.dispose();
          crosshairtraceBuilder_ = null;
        }
        camerapositionX_ = 0;
        camerapositionY_ = 0;
        clickbehavior_ = 0;
        statspanel_ = 0;
        shoppanel_ = 0;
        statsDropdown_ = 0;
        statsDropdownSort_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kz.moltenhaze.proto.dota.DotaUsercmd.internal_static_CDota2UserCmdPB_descriptor;
      }

      @java.lang.Override
      public kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB getDefaultInstanceForType() {
        return kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB.getDefaultInstance();
      }

      @java.lang.Override
      public kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB build() {
        kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB buildPartial() {
        kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB result = new kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.base_ = baseBuilder_ == null
              ? base_
              : baseBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.spectatorQueryUnitEntindex_ = spectatorQueryUnitEntindex_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.crosshairtrace_ = crosshairtraceBuilder_ == null
              ? crosshairtrace_
              : crosshairtraceBuilder_.build();
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.camerapositionX_ = camerapositionX_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.camerapositionY_ = camerapositionY_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.clickbehavior_ = clickbehavior_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.statspanel_ = statspanel_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.shoppanel_ = shoppanel_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.statsDropdown_ = statsDropdown_;
          to_bitField0_ |= 0x00000100;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.statsDropdownSort_ = statsDropdownSort_;
          to_bitField0_ |= 0x00000200;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB) {
          return mergeFrom((kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB other) {
        if (other == kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB.getDefaultInstance()) return this;
        if (other.hasBase()) {
          mergeBase(other.getBase());
        }
        if (other.hasSpectatorQueryUnitEntindex()) {
          setSpectatorQueryUnitEntindex(other.getSpectatorQueryUnitEntindex());
        }
        if (other.hasCrosshairtrace()) {
          mergeCrosshairtrace(other.getCrosshairtrace());
        }
        if (other.hasCamerapositionX()) {
          setCamerapositionX(other.getCamerapositionX());
        }
        if (other.hasCamerapositionY()) {
          setCamerapositionY(other.getCamerapositionY());
        }
        if (other.hasClickbehavior()) {
          setClickbehavior(other.getClickbehavior());
        }
        if (other.hasStatspanel()) {
          setStatspanel(other.getStatspanel());
        }
        if (other.hasShoppanel()) {
          setShoppanel(other.getShoppanel());
        }
        if (other.hasStatsDropdown()) {
          setStatsDropdown(other.getStatsDropdown());
        }
        if (other.hasStatsDropdownSort()) {
          setStatsDropdownSort(other.getStatsDropdownSort());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getBaseFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                spectatorQueryUnitEntindex_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                input.readMessage(
                    getCrosshairtraceFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                camerapositionX_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                camerapositionY_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                clickbehavior_ = input.readUInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                statspanel_ = input.readUInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 64: {
                shoppanel_ = input.readUInt32();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 72: {
                statsDropdown_ = input.readUInt32();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              case 80: {
                statsDropdownSort_ = input.readUInt32();
                bitField0_ |= 0x00000200;
                break;
              } // case 80
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPB base_;
      private com.google.protobuf.SingleFieldBuilder<
          kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPB, kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPB.Builder, kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPBOrBuilder> baseBuilder_;
      /**
       * <code>optional .CBaseUserCmdPB base = 1;</code>
       * @return Whether the base field is set.
       */
      public boolean hasBase() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .CBaseUserCmdPB base = 1;</code>
       * @return The base.
       */
      public kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPB getBase() {
        if (baseBuilder_ == null) {
          return base_ == null ? kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPB.getDefaultInstance() : base_;
        } else {
          return baseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .CBaseUserCmdPB base = 1;</code>
       */
      public Builder setBase(kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPB value) {
        if (baseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          base_ = value;
        } else {
          baseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .CBaseUserCmdPB base = 1;</code>
       */
      public Builder setBase(
          kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPB.Builder builderForValue) {
        if (baseBuilder_ == null) {
          base_ = builderForValue.build();
        } else {
          baseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .CBaseUserCmdPB base = 1;</code>
       */
      public Builder mergeBase(kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPB value) {
        if (baseBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            base_ != null &&
            base_ != kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPB.getDefaultInstance()) {
            getBaseBuilder().mergeFrom(value);
          } else {
            base_ = value;
          }
        } else {
          baseBuilder_.mergeFrom(value);
        }
        if (base_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .CBaseUserCmdPB base = 1;</code>
       */
      public Builder clearBase() {
        bitField0_ = (bitField0_ & ~0x00000001);
        base_ = null;
        if (baseBuilder_ != null) {
          baseBuilder_.dispose();
          baseBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .CBaseUserCmdPB base = 1;</code>
       */
      public kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPB.Builder getBaseBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getBaseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .CBaseUserCmdPB base = 1;</code>
       */
      public kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPBOrBuilder getBaseOrBuilder() {
        if (baseBuilder_ != null) {
          return baseBuilder_.getMessageOrBuilder();
        } else {
          return base_ == null ?
              kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPB.getDefaultInstance() : base_;
        }
      }
      /**
       * <code>optional .CBaseUserCmdPB base = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPB, kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPB.Builder, kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPBOrBuilder> 
          getBaseFieldBuilder() {
        if (baseBuilder_ == null) {
          baseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPB, kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPB.Builder, kz.moltenhaze.proto.dota.Usercmd.CBaseUserCmdPBOrBuilder>(
                  getBase(),
                  getParentForChildren(),
                  isClean());
          base_ = null;
        }
        return baseBuilder_;
      }

      private int spectatorQueryUnitEntindex_ ;
      /**
       * <code>optional int32 spectator_query_unit_entindex = 2;</code>
       * @return Whether the spectatorQueryUnitEntindex field is set.
       */
      @java.lang.Override
      public boolean hasSpectatorQueryUnitEntindex() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 spectator_query_unit_entindex = 2;</code>
       * @return The spectatorQueryUnitEntindex.
       */
      @java.lang.Override
      public int getSpectatorQueryUnitEntindex() {
        return spectatorQueryUnitEntindex_;
      }
      /**
       * <code>optional int32 spectator_query_unit_entindex = 2;</code>
       * @param value The spectatorQueryUnitEntindex to set.
       * @return This builder for chaining.
       */
      public Builder setSpectatorQueryUnitEntindex(int value) {

        spectatorQueryUnitEntindex_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 spectator_query_unit_entindex = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSpectatorQueryUnitEntindex() {
        bitField0_ = (bitField0_ & ~0x00000002);
        spectatorQueryUnitEntindex_ = 0;
        onChanged();
        return this;
      }

      private kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVector crosshairtrace_;
      private com.google.protobuf.SingleFieldBuilder<
          kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVector, kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVector.Builder, kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVectorOrBuilder> crosshairtraceBuilder_;
      /**
       * <code>optional .CMsgVector crosshairtrace = 3;</code>
       * @return Whether the crosshairtrace field is set.
       */
      public boolean hasCrosshairtrace() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .CMsgVector crosshairtrace = 3;</code>
       * @return The crosshairtrace.
       */
      public kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVector getCrosshairtrace() {
        if (crosshairtraceBuilder_ == null) {
          return crosshairtrace_ == null ? kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVector.getDefaultInstance() : crosshairtrace_;
        } else {
          return crosshairtraceBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .CMsgVector crosshairtrace = 3;</code>
       */
      public Builder setCrosshairtrace(kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVector value) {
        if (crosshairtraceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          crosshairtrace_ = value;
        } else {
          crosshairtraceBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional .CMsgVector crosshairtrace = 3;</code>
       */
      public Builder setCrosshairtrace(
          kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVector.Builder builderForValue) {
        if (crosshairtraceBuilder_ == null) {
          crosshairtrace_ = builderForValue.build();
        } else {
          crosshairtraceBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional .CMsgVector crosshairtrace = 3;</code>
       */
      public Builder mergeCrosshairtrace(kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVector value) {
        if (crosshairtraceBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            crosshairtrace_ != null &&
            crosshairtrace_ != kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVector.getDefaultInstance()) {
            getCrosshairtraceBuilder().mergeFrom(value);
          } else {
            crosshairtrace_ = value;
          }
        } else {
          crosshairtraceBuilder_.mergeFrom(value);
        }
        if (crosshairtrace_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .CMsgVector crosshairtrace = 3;</code>
       */
      public Builder clearCrosshairtrace() {
        bitField0_ = (bitField0_ & ~0x00000004);
        crosshairtrace_ = null;
        if (crosshairtraceBuilder_ != null) {
          crosshairtraceBuilder_.dispose();
          crosshairtraceBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .CMsgVector crosshairtrace = 3;</code>
       */
      public kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVector.Builder getCrosshairtraceBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getCrosshairtraceFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .CMsgVector crosshairtrace = 3;</code>
       */
      public kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVectorOrBuilder getCrosshairtraceOrBuilder() {
        if (crosshairtraceBuilder_ != null) {
          return crosshairtraceBuilder_.getMessageOrBuilder();
        } else {
          return crosshairtrace_ == null ?
              kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVector.getDefaultInstance() : crosshairtrace_;
        }
      }
      /**
       * <code>optional .CMsgVector crosshairtrace = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVector, kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVector.Builder, kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVectorOrBuilder> 
          getCrosshairtraceFieldBuilder() {
        if (crosshairtraceBuilder_ == null) {
          crosshairtraceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVector, kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVector.Builder, kz.moltenhaze.proto.dota.Networkbasetypes.CMsgVectorOrBuilder>(
                  getCrosshairtrace(),
                  getParentForChildren(),
                  isClean());
          crosshairtrace_ = null;
        }
        return crosshairtraceBuilder_;
      }

      private int camerapositionX_ ;
      /**
       * <code>optional int32 cameraposition_x = 4;</code>
       * @return Whether the camerapositionX field is set.
       */
      @java.lang.Override
      public boolean hasCamerapositionX() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 cameraposition_x = 4;</code>
       * @return The camerapositionX.
       */
      @java.lang.Override
      public int getCamerapositionX() {
        return camerapositionX_;
      }
      /**
       * <code>optional int32 cameraposition_x = 4;</code>
       * @param value The camerapositionX to set.
       * @return This builder for chaining.
       */
      public Builder setCamerapositionX(int value) {

        camerapositionX_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cameraposition_x = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCamerapositionX() {
        bitField0_ = (bitField0_ & ~0x00000008);
        camerapositionX_ = 0;
        onChanged();
        return this;
      }

      private int camerapositionY_ ;
      /**
       * <code>optional int32 cameraposition_y = 5;</code>
       * @return Whether the camerapositionY field is set.
       */
      @java.lang.Override
      public boolean hasCamerapositionY() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional int32 cameraposition_y = 5;</code>
       * @return The camerapositionY.
       */
      @java.lang.Override
      public int getCamerapositionY() {
        return camerapositionY_;
      }
      /**
       * <code>optional int32 cameraposition_y = 5;</code>
       * @param value The camerapositionY to set.
       * @return This builder for chaining.
       */
      public Builder setCamerapositionY(int value) {

        camerapositionY_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cameraposition_y = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCamerapositionY() {
        bitField0_ = (bitField0_ & ~0x00000010);
        camerapositionY_ = 0;
        onChanged();
        return this;
      }

      private int clickbehavior_ ;
      /**
       * <code>optional uint32 clickbehavior = 6;</code>
       * @return Whether the clickbehavior field is set.
       */
      @java.lang.Override
      public boolean hasClickbehavior() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional uint32 clickbehavior = 6;</code>
       * @return The clickbehavior.
       */
      @java.lang.Override
      public int getClickbehavior() {
        return clickbehavior_;
      }
      /**
       * <code>optional uint32 clickbehavior = 6;</code>
       * @param value The clickbehavior to set.
       * @return This builder for chaining.
       */
      public Builder setClickbehavior(int value) {

        clickbehavior_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 clickbehavior = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearClickbehavior() {
        bitField0_ = (bitField0_ & ~0x00000020);
        clickbehavior_ = 0;
        onChanged();
        return this;
      }

      private int statspanel_ ;
      /**
       * <code>optional uint32 statspanel = 7;</code>
       * @return Whether the statspanel field is set.
       */
      @java.lang.Override
      public boolean hasStatspanel() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional uint32 statspanel = 7;</code>
       * @return The statspanel.
       */
      @java.lang.Override
      public int getStatspanel() {
        return statspanel_;
      }
      /**
       * <code>optional uint32 statspanel = 7;</code>
       * @param value The statspanel to set.
       * @return This builder for chaining.
       */
      public Builder setStatspanel(int value) {

        statspanel_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 statspanel = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatspanel() {
        bitField0_ = (bitField0_ & ~0x00000040);
        statspanel_ = 0;
        onChanged();
        return this;
      }

      private int shoppanel_ ;
      /**
       * <code>optional uint32 shoppanel = 8;</code>
       * @return Whether the shoppanel field is set.
       */
      @java.lang.Override
      public boolean hasShoppanel() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional uint32 shoppanel = 8;</code>
       * @return The shoppanel.
       */
      @java.lang.Override
      public int getShoppanel() {
        return shoppanel_;
      }
      /**
       * <code>optional uint32 shoppanel = 8;</code>
       * @param value The shoppanel to set.
       * @return This builder for chaining.
       */
      public Builder setShoppanel(int value) {

        shoppanel_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 shoppanel = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearShoppanel() {
        bitField0_ = (bitField0_ & ~0x00000080);
        shoppanel_ = 0;
        onChanged();
        return this;
      }

      private int statsDropdown_ ;
      /**
       * <code>optional uint32 stats_dropdown = 9;</code>
       * @return Whether the statsDropdown field is set.
       */
      @java.lang.Override
      public boolean hasStatsDropdown() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional uint32 stats_dropdown = 9;</code>
       * @return The statsDropdown.
       */
      @java.lang.Override
      public int getStatsDropdown() {
        return statsDropdown_;
      }
      /**
       * <code>optional uint32 stats_dropdown = 9;</code>
       * @param value The statsDropdown to set.
       * @return This builder for chaining.
       */
      public Builder setStatsDropdown(int value) {

        statsDropdown_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 stats_dropdown = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatsDropdown() {
        bitField0_ = (bitField0_ & ~0x00000100);
        statsDropdown_ = 0;
        onChanged();
        return this;
      }

      private int statsDropdownSort_ ;
      /**
       * <code>optional uint32 stats_dropdown_sort = 10;</code>
       * @return Whether the statsDropdownSort field is set.
       */
      @java.lang.Override
      public boolean hasStatsDropdownSort() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <code>optional uint32 stats_dropdown_sort = 10;</code>
       * @return The statsDropdownSort.
       */
      @java.lang.Override
      public int getStatsDropdownSort() {
        return statsDropdownSort_;
      }
      /**
       * <code>optional uint32 stats_dropdown_sort = 10;</code>
       * @param value The statsDropdownSort to set.
       * @return This builder for chaining.
       */
      public Builder setStatsDropdownSort(int value) {

        statsDropdownSort_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 stats_dropdown_sort = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatsDropdownSort() {
        bitField0_ = (bitField0_ & ~0x00000200);
        statsDropdownSort_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CDota2UserCmdPB)
    }

    // @@protoc_insertion_point(class_scope:CDota2UserCmdPB)
    private static final kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB();
    }

    public static kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CDota2UserCmdPB>
        PARSER = new com.google.protobuf.AbstractParser<CDota2UserCmdPB>() {
      @java.lang.Override
      public CDota2UserCmdPB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CDota2UserCmdPB> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CDota2UserCmdPB> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public kz.moltenhaze.proto.dota.DotaUsercmd.CDota2UserCmdPB getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CDota2UserCmdPB_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CDota2UserCmdPB_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022dota_usercmd.proto\032\026networkbasetypes.p" +
      "roto\032\rusercmd.proto\"\243\002\n\017CDota2UserCmdPB\022" +
      "\035\n\004base\030\001 \001(\0132\017.CBaseUserCmdPB\022%\n\035specta" +
      "tor_query_unit_entindex\030\002 \001(\005\022#\n\016crossha" +
      "irtrace\030\003 \001(\0132\013.CMsgVector\022\030\n\020cameraposi" +
      "tion_x\030\004 \001(\005\022\030\n\020cameraposition_y\030\005 \001(\005\022\025" +
      "\n\rclickbehavior\030\006 \001(\r\022\022\n\nstatspanel\030\007 \001(" +
      "\r\022\021\n\tshoppanel\030\010 \001(\r\022\026\n\016stats_dropdown\030\t" +
      " \001(\r\022\033\n\023stats_dropdown_sort\030\n \001(\rB\032\n\030kz." +
      "moltenhaze.proto.dota"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          kz.moltenhaze.proto.dota.Networkbasetypes.getDescriptor(),
          kz.moltenhaze.proto.dota.Usercmd.getDescriptor(),
        });
    internal_static_CDota2UserCmdPB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CDota2UserCmdPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CDota2UserCmdPB_descriptor,
        new java.lang.String[] { "Base", "SpectatorQueryUnitEntindex", "Crosshairtrace", "CamerapositionX", "CamerapositionY", "Clickbehavior", "Statspanel", "Shoppanel", "StatsDropdown", "StatsDropdownSort", });
    descriptor.resolveAllFeaturesImmutable();
    kz.moltenhaze.proto.dota.Networkbasetypes.getDescriptor();
    kz.moltenhaze.proto.dota.Usercmd.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
