// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: networksystem_protomessages.proto
// Protobuf Java Version: 4.28.0

package kz.moltenhaze.proto.dota;

public final class NetworksystemProtomessages {
  private NetworksystemProtomessages() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "",
      NetworksystemProtomessages.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NetMessageSplitscreenUserChangedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NetMessageSplitscreenUserChanged)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 slot = 1;</code>
     * @return Whether the slot field is set.
     */
    boolean hasSlot();
    /**
     * <code>optional uint32 slot = 1;</code>
     * @return The slot.
     */
    int getSlot();
  }
  /**
   * Protobuf type {@code NetMessageSplitscreenUserChanged}
   */
  public static final class NetMessageSplitscreenUserChanged extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:NetMessageSplitscreenUserChanged)
      NetMessageSplitscreenUserChangedOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 0,
        /* suffix= */ "",
        NetMessageSplitscreenUserChanged.class.getName());
    }
    // Use NetMessageSplitscreenUserChanged.newBuilder() to construct.
    private NetMessageSplitscreenUserChanged(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private NetMessageSplitscreenUserChanged() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kz.moltenhaze.proto.dota.NetworksystemProtomessages.internal_static_NetMessageSplitscreenUserChanged_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kz.moltenhaze.proto.dota.NetworksystemProtomessages.internal_static_NetMessageSplitscreenUserChanged_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged.class, kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged.Builder.class);
    }

    private int bitField0_;
    public static final int SLOT_FIELD_NUMBER = 1;
    private int slot_ = 0;
    /**
     * <code>optional uint32 slot = 1;</code>
     * @return Whether the slot field is set.
     */
    @java.lang.Override
    public boolean hasSlot() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint32 slot = 1;</code>
     * @return The slot.
     */
    @java.lang.Override
    public int getSlot() {
      return slot_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, slot_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, slot_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged)) {
        return super.equals(obj);
      }
      kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged other = (kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged) obj;

      if (hasSlot() != other.hasSlot()) return false;
      if (hasSlot()) {
        if (getSlot()
            != other.getSlot()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSlot()) {
        hash = (37 * hash) + SLOT_FIELD_NUMBER;
        hash = (53 * hash) + getSlot();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetMessageSplitscreenUserChanged}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NetMessageSplitscreenUserChanged)
        kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChangedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kz.moltenhaze.proto.dota.NetworksystemProtomessages.internal_static_NetMessageSplitscreenUserChanged_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kz.moltenhaze.proto.dota.NetworksystemProtomessages.internal_static_NetMessageSplitscreenUserChanged_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged.class, kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged.Builder.class);
      }

      // Construct using kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        slot_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kz.moltenhaze.proto.dota.NetworksystemProtomessages.internal_static_NetMessageSplitscreenUserChanged_descriptor;
      }

      @java.lang.Override
      public kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged getDefaultInstanceForType() {
        return kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged.getDefaultInstance();
      }

      @java.lang.Override
      public kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged build() {
        kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged buildPartial() {
        kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged result = new kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.slot_ = slot_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged) {
          return mergeFrom((kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged other) {
        if (other == kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged.getDefaultInstance()) return this;
        if (other.hasSlot()) {
          setSlot(other.getSlot());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                slot_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int slot_ ;
      /**
       * <code>optional uint32 slot = 1;</code>
       * @return Whether the slot field is set.
       */
      @java.lang.Override
      public boolean hasSlot() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint32 slot = 1;</code>
       * @return The slot.
       */
      @java.lang.Override
      public int getSlot() {
        return slot_;
      }
      /**
       * <code>optional uint32 slot = 1;</code>
       * @param value The slot to set.
       * @return This builder for chaining.
       */
      public Builder setSlot(int value) {

        slot_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 slot = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSlot() {
        bitField0_ = (bitField0_ & ~0x00000001);
        slot_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NetMessageSplitscreenUserChanged)
    }

    // @@protoc_insertion_point(class_scope:NetMessageSplitscreenUserChanged)
    private static final kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged();
    }

    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NetMessageSplitscreenUserChanged>
        PARSER = new com.google.protobuf.AbstractParser<NetMessageSplitscreenUserChanged>() {
      @java.lang.Override
      public NetMessageSplitscreenUserChanged parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NetMessageSplitscreenUserChanged> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NetMessageSplitscreenUserChanged> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageSplitscreenUserChanged getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NetMessageConnectionClosedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NetMessageConnectionClosed)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 reason = 1;</code>
     * @return Whether the reason field is set.
     */
    boolean hasReason();
    /**
     * <code>optional uint32 reason = 1;</code>
     * @return The reason.
     */
    int getReason();
  }
  /**
   * Protobuf type {@code NetMessageConnectionClosed}
   */
  public static final class NetMessageConnectionClosed extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:NetMessageConnectionClosed)
      NetMessageConnectionClosedOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 0,
        /* suffix= */ "",
        NetMessageConnectionClosed.class.getName());
    }
    // Use NetMessageConnectionClosed.newBuilder() to construct.
    private NetMessageConnectionClosed(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private NetMessageConnectionClosed() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kz.moltenhaze.proto.dota.NetworksystemProtomessages.internal_static_NetMessageConnectionClosed_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kz.moltenhaze.proto.dota.NetworksystemProtomessages.internal_static_NetMessageConnectionClosed_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed.class, kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed.Builder.class);
    }

    private int bitField0_;
    public static final int REASON_FIELD_NUMBER = 1;
    private int reason_ = 0;
    /**
     * <code>optional uint32 reason = 1;</code>
     * @return Whether the reason field is set.
     */
    @java.lang.Override
    public boolean hasReason() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint32 reason = 1;</code>
     * @return The reason.
     */
    @java.lang.Override
    public int getReason() {
      return reason_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, reason_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, reason_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed)) {
        return super.equals(obj);
      }
      kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed other = (kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed) obj;

      if (hasReason() != other.hasReason()) return false;
      if (hasReason()) {
        if (getReason()
            != other.getReason()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasReason()) {
        hash = (37 * hash) + REASON_FIELD_NUMBER;
        hash = (53 * hash) + getReason();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetMessageConnectionClosed}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NetMessageConnectionClosed)
        kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kz.moltenhaze.proto.dota.NetworksystemProtomessages.internal_static_NetMessageConnectionClosed_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kz.moltenhaze.proto.dota.NetworksystemProtomessages.internal_static_NetMessageConnectionClosed_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed.class, kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed.Builder.class);
      }

      // Construct using kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        reason_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kz.moltenhaze.proto.dota.NetworksystemProtomessages.internal_static_NetMessageConnectionClosed_descriptor;
      }

      @java.lang.Override
      public kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed getDefaultInstanceForType() {
        return kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed.getDefaultInstance();
      }

      @java.lang.Override
      public kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed build() {
        kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed buildPartial() {
        kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed result = new kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.reason_ = reason_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed) {
          return mergeFrom((kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed other) {
        if (other == kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed.getDefaultInstance()) return this;
        if (other.hasReason()) {
          setReason(other.getReason());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                reason_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int reason_ ;
      /**
       * <code>optional uint32 reason = 1;</code>
       * @return Whether the reason field is set.
       */
      @java.lang.Override
      public boolean hasReason() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint32 reason = 1;</code>
       * @return The reason.
       */
      @java.lang.Override
      public int getReason() {
        return reason_;
      }
      /**
       * <code>optional uint32 reason = 1;</code>
       * @param value The reason to set.
       * @return This builder for chaining.
       */
      public Builder setReason(int value) {

        reason_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 reason = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearReason() {
        bitField0_ = (bitField0_ & ~0x00000001);
        reason_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NetMessageConnectionClosed)
    }

    // @@protoc_insertion_point(class_scope:NetMessageConnectionClosed)
    private static final kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed();
    }

    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NetMessageConnectionClosed>
        PARSER = new com.google.protobuf.AbstractParser<NetMessageConnectionClosed>() {
      @java.lang.Override
      public NetMessageConnectionClosed parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NetMessageConnectionClosed> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NetMessageConnectionClosed> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionClosed getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NetMessageConnectionCrashedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NetMessageConnectionCrashed)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 reason = 1;</code>
     * @return Whether the reason field is set.
     */
    boolean hasReason();
    /**
     * <code>optional uint32 reason = 1;</code>
     * @return The reason.
     */
    int getReason();
  }
  /**
   * Protobuf type {@code NetMessageConnectionCrashed}
   */
  public static final class NetMessageConnectionCrashed extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:NetMessageConnectionCrashed)
      NetMessageConnectionCrashedOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 0,
        /* suffix= */ "",
        NetMessageConnectionCrashed.class.getName());
    }
    // Use NetMessageConnectionCrashed.newBuilder() to construct.
    private NetMessageConnectionCrashed(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private NetMessageConnectionCrashed() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kz.moltenhaze.proto.dota.NetworksystemProtomessages.internal_static_NetMessageConnectionCrashed_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kz.moltenhaze.proto.dota.NetworksystemProtomessages.internal_static_NetMessageConnectionCrashed_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed.class, kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed.Builder.class);
    }

    private int bitField0_;
    public static final int REASON_FIELD_NUMBER = 1;
    private int reason_ = 0;
    /**
     * <code>optional uint32 reason = 1;</code>
     * @return Whether the reason field is set.
     */
    @java.lang.Override
    public boolean hasReason() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint32 reason = 1;</code>
     * @return The reason.
     */
    @java.lang.Override
    public int getReason() {
      return reason_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, reason_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, reason_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed)) {
        return super.equals(obj);
      }
      kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed other = (kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed) obj;

      if (hasReason() != other.hasReason()) return false;
      if (hasReason()) {
        if (getReason()
            != other.getReason()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasReason()) {
        hash = (37 * hash) + REASON_FIELD_NUMBER;
        hash = (53 * hash) + getReason();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetMessageConnectionCrashed}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NetMessageConnectionCrashed)
        kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kz.moltenhaze.proto.dota.NetworksystemProtomessages.internal_static_NetMessageConnectionCrashed_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kz.moltenhaze.proto.dota.NetworksystemProtomessages.internal_static_NetMessageConnectionCrashed_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed.class, kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed.Builder.class);
      }

      // Construct using kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        reason_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kz.moltenhaze.proto.dota.NetworksystemProtomessages.internal_static_NetMessageConnectionCrashed_descriptor;
      }

      @java.lang.Override
      public kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed getDefaultInstanceForType() {
        return kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed.getDefaultInstance();
      }

      @java.lang.Override
      public kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed build() {
        kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed buildPartial() {
        kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed result = new kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.reason_ = reason_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed) {
          return mergeFrom((kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed other) {
        if (other == kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed.getDefaultInstance()) return this;
        if (other.hasReason()) {
          setReason(other.getReason());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                reason_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int reason_ ;
      /**
       * <code>optional uint32 reason = 1;</code>
       * @return Whether the reason field is set.
       */
      @java.lang.Override
      public boolean hasReason() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint32 reason = 1;</code>
       * @return The reason.
       */
      @java.lang.Override
      public int getReason() {
        return reason_;
      }
      /**
       * <code>optional uint32 reason = 1;</code>
       * @param value The reason to set.
       * @return This builder for chaining.
       */
      public Builder setReason(int value) {

        reason_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 reason = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearReason() {
        bitField0_ = (bitField0_ & ~0x00000001);
        reason_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NetMessageConnectionCrashed)
    }

    // @@protoc_insertion_point(class_scope:NetMessageConnectionCrashed)
    private static final kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed();
    }

    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NetMessageConnectionCrashed>
        PARSER = new com.google.protobuf.AbstractParser<NetMessageConnectionCrashed>() {
      @java.lang.Override
      public NetMessageConnectionCrashed parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NetMessageConnectionCrashed> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NetMessageConnectionCrashed> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessageConnectionCrashed getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NetMessagePacketStartOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NetMessagePacketStart)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code NetMessagePacketStart}
   */
  public static final class NetMessagePacketStart extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:NetMessagePacketStart)
      NetMessagePacketStartOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 0,
        /* suffix= */ "",
        NetMessagePacketStart.class.getName());
    }
    // Use NetMessagePacketStart.newBuilder() to construct.
    private NetMessagePacketStart(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private NetMessagePacketStart() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kz.moltenhaze.proto.dota.NetworksystemProtomessages.internal_static_NetMessagePacketStart_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kz.moltenhaze.proto.dota.NetworksystemProtomessages.internal_static_NetMessagePacketStart_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart.class, kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart)) {
        return super.equals(obj);
      }
      kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart other = (kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetMessagePacketStart}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NetMessagePacketStart)
        kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStartOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kz.moltenhaze.proto.dota.NetworksystemProtomessages.internal_static_NetMessagePacketStart_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kz.moltenhaze.proto.dota.NetworksystemProtomessages.internal_static_NetMessagePacketStart_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart.class, kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart.Builder.class);
      }

      // Construct using kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kz.moltenhaze.proto.dota.NetworksystemProtomessages.internal_static_NetMessagePacketStart_descriptor;
      }

      @java.lang.Override
      public kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart getDefaultInstanceForType() {
        return kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart.getDefaultInstance();
      }

      @java.lang.Override
      public kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart build() {
        kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart buildPartial() {
        kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart result = new kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart) {
          return mergeFrom((kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart other) {
        if (other == kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NetMessagePacketStart)
    }

    // @@protoc_insertion_point(class_scope:NetMessagePacketStart)
    private static final kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart();
    }

    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NetMessagePacketStart>
        PARSER = new com.google.protobuf.AbstractParser<NetMessagePacketStart>() {
      @java.lang.Override
      public NetMessagePacketStart parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NetMessagePacketStart> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NetMessagePacketStart> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketStart getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NetMessagePacketEndOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NetMessagePacketEnd)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code NetMessagePacketEnd}
   */
  public static final class NetMessagePacketEnd extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:NetMessagePacketEnd)
      NetMessagePacketEndOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 0,
        /* suffix= */ "",
        NetMessagePacketEnd.class.getName());
    }
    // Use NetMessagePacketEnd.newBuilder() to construct.
    private NetMessagePacketEnd(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private NetMessagePacketEnd() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kz.moltenhaze.proto.dota.NetworksystemProtomessages.internal_static_NetMessagePacketEnd_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kz.moltenhaze.proto.dota.NetworksystemProtomessages.internal_static_NetMessagePacketEnd_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd.class, kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd)) {
        return super.equals(obj);
      }
      kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd other = (kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetMessagePacketEnd}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NetMessagePacketEnd)
        kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEndOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kz.moltenhaze.proto.dota.NetworksystemProtomessages.internal_static_NetMessagePacketEnd_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kz.moltenhaze.proto.dota.NetworksystemProtomessages.internal_static_NetMessagePacketEnd_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd.class, kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd.Builder.class);
      }

      // Construct using kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kz.moltenhaze.proto.dota.NetworksystemProtomessages.internal_static_NetMessagePacketEnd_descriptor;
      }

      @java.lang.Override
      public kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd getDefaultInstanceForType() {
        return kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd.getDefaultInstance();
      }

      @java.lang.Override
      public kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd build() {
        kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd buildPartial() {
        kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd result = new kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd) {
          return mergeFrom((kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd other) {
        if (other == kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NetMessagePacketEnd)
    }

    // @@protoc_insertion_point(class_scope:NetMessagePacketEnd)
    private static final kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd();
    }

    public static kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NetMessagePacketEnd>
        PARSER = new com.google.protobuf.AbstractParser<NetMessagePacketEnd>() {
      @java.lang.Override
      public NetMessagePacketEnd parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NetMessagePacketEnd> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NetMessagePacketEnd> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public kz.moltenhaze.proto.dota.NetworksystemProtomessages.NetMessagePacketEnd getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NetMessageSplitscreenUserChanged_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NetMessageSplitscreenUserChanged_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NetMessageConnectionClosed_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NetMessageConnectionClosed_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NetMessageConnectionCrashed_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NetMessageConnectionCrashed_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NetMessagePacketStart_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NetMessagePacketStart_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NetMessagePacketEnd_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NetMessagePacketEnd_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!networksystem_protomessages.proto\"0\n N" +
      "etMessageSplitscreenUserChanged\022\014\n\004slot\030" +
      "\001 \001(\r\",\n\032NetMessageConnectionClosed\022\016\n\006r" +
      "eason\030\001 \001(\r\"-\n\033NetMessageConnectionCrash" +
      "ed\022\016\n\006reason\030\001 \001(\r\"\027\n\025NetMessagePacketSt" +
      "art\"\025\n\023NetMessagePacketEndB\032\n\030kz.moltenh" +
      "aze.proto.dota"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_NetMessageSplitscreenUserChanged_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NetMessageSplitscreenUserChanged_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NetMessageSplitscreenUserChanged_descriptor,
        new java.lang.String[] { "Slot", });
    internal_static_NetMessageConnectionClosed_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_NetMessageConnectionClosed_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NetMessageConnectionClosed_descriptor,
        new java.lang.String[] { "Reason", });
    internal_static_NetMessageConnectionCrashed_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_NetMessageConnectionCrashed_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NetMessageConnectionCrashed_descriptor,
        new java.lang.String[] { "Reason", });
    internal_static_NetMessagePacketStart_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_NetMessagePacketStart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NetMessagePacketStart_descriptor,
        new java.lang.String[] { });
    internal_static_NetMessagePacketEnd_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_NetMessagePacketEnd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NetMessagePacketEnd_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
