// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: uifontfile_format.proto
// Protobuf Java Version: 4.28.0

package kz.moltenhaze.proto.dota;

public final class UifontfileFormat {
  private UifontfileFormat() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "",
      UifontfileFormat.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CUIFontFilePBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CUIFontFilePB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string font_file_name = 1;</code>
     * @return Whether the fontFileName field is set.
     */
    boolean hasFontFileName();
    /**
     * <code>optional string font_file_name = 1;</code>
     * @return The fontFileName.
     */
    java.lang.String getFontFileName();
    /**
     * <code>optional string font_file_name = 1;</code>
     * @return The bytes for fontFileName.
     */
    com.google.protobuf.ByteString
        getFontFileNameBytes();

    /**
     * <code>optional bytes opentype_font_data = 2;</code>
     * @return Whether the opentypeFontData field is set.
     */
    boolean hasOpentypeFontData();
    /**
     * <code>optional bytes opentype_font_data = 2;</code>
     * @return The opentypeFontData.
     */
    com.google.protobuf.ByteString getOpentypeFontData();
  }
  /**
   * Protobuf type {@code CUIFontFilePB}
   */
  public static final class CUIFontFilePB extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CUIFontFilePB)
      CUIFontFilePBOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 0,
        /* suffix= */ "",
        CUIFontFilePB.class.getName());
    }
    // Use CUIFontFilePB.newBuilder() to construct.
    private CUIFontFilePB(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CUIFontFilePB() {
      fontFileName_ = "";
      opentypeFontData_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kz.moltenhaze.proto.dota.UifontfileFormat.internal_static_CUIFontFilePB_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kz.moltenhaze.proto.dota.UifontfileFormat.internal_static_CUIFontFilePB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB.class, kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB.Builder.class);
    }

    private int bitField0_;
    public static final int FONT_FILE_NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object fontFileName_ = "";
    /**
     * <code>optional string font_file_name = 1;</code>
     * @return Whether the fontFileName field is set.
     */
    @java.lang.Override
    public boolean hasFontFileName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string font_file_name = 1;</code>
     * @return The fontFileName.
     */
    @java.lang.Override
    public java.lang.String getFontFileName() {
      java.lang.Object ref = fontFileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fontFileName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string font_file_name = 1;</code>
     * @return The bytes for fontFileName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFontFileNameBytes() {
      java.lang.Object ref = fontFileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fontFileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPENTYPE_FONT_DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString opentypeFontData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes opentype_font_data = 2;</code>
     * @return Whether the opentypeFontData field is set.
     */
    @java.lang.Override
    public boolean hasOpentypeFontData() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bytes opentype_font_data = 2;</code>
     * @return The opentypeFontData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getOpentypeFontData() {
      return opentypeFontData_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, fontFileName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBytes(2, opentypeFontData_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, fontFileName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, opentypeFontData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB)) {
        return super.equals(obj);
      }
      kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB other = (kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB) obj;

      if (hasFontFileName() != other.hasFontFileName()) return false;
      if (hasFontFileName()) {
        if (!getFontFileName()
            .equals(other.getFontFileName())) return false;
      }
      if (hasOpentypeFontData() != other.hasOpentypeFontData()) return false;
      if (hasOpentypeFontData()) {
        if (!getOpentypeFontData()
            .equals(other.getOpentypeFontData())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFontFileName()) {
        hash = (37 * hash) + FONT_FILE_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getFontFileName().hashCode();
      }
      if (hasOpentypeFontData()) {
        hash = (37 * hash) + OPENTYPE_FONT_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getOpentypeFontData().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CUIFontFilePB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CUIFontFilePB)
        kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kz.moltenhaze.proto.dota.UifontfileFormat.internal_static_CUIFontFilePB_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kz.moltenhaze.proto.dota.UifontfileFormat.internal_static_CUIFontFilePB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB.class, kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB.Builder.class);
      }

      // Construct using kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        fontFileName_ = "";
        opentypeFontData_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kz.moltenhaze.proto.dota.UifontfileFormat.internal_static_CUIFontFilePB_descriptor;
      }

      @java.lang.Override
      public kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB getDefaultInstanceForType() {
        return kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB.getDefaultInstance();
      }

      @java.lang.Override
      public kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB build() {
        kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB buildPartial() {
        kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB result = new kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.fontFileName_ = fontFileName_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.opentypeFontData_ = opentypeFontData_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB) {
          return mergeFrom((kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB other) {
        if (other == kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB.getDefaultInstance()) return this;
        if (other.hasFontFileName()) {
          fontFileName_ = other.fontFileName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasOpentypeFontData()) {
          setOpentypeFontData(other.getOpentypeFontData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                fontFileName_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                opentypeFontData_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object fontFileName_ = "";
      /**
       * <code>optional string font_file_name = 1;</code>
       * @return Whether the fontFileName field is set.
       */
      public boolean hasFontFileName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string font_file_name = 1;</code>
       * @return The fontFileName.
       */
      public java.lang.String getFontFileName() {
        java.lang.Object ref = fontFileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fontFileName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string font_file_name = 1;</code>
       * @return The bytes for fontFileName.
       */
      public com.google.protobuf.ByteString
          getFontFileNameBytes() {
        java.lang.Object ref = fontFileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fontFileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string font_file_name = 1;</code>
       * @param value The fontFileName to set.
       * @return This builder for chaining.
       */
      public Builder setFontFileName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        fontFileName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string font_file_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFontFileName() {
        fontFileName_ = getDefaultInstance().getFontFileName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string font_file_name = 1;</code>
       * @param value The bytes for fontFileName to set.
       * @return This builder for chaining.
       */
      public Builder setFontFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        fontFileName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString opentypeFontData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes opentype_font_data = 2;</code>
       * @return Whether the opentypeFontData field is set.
       */
      @java.lang.Override
      public boolean hasOpentypeFontData() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bytes opentype_font_data = 2;</code>
       * @return The opentypeFontData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getOpentypeFontData() {
        return opentypeFontData_;
      }
      /**
       * <code>optional bytes opentype_font_data = 2;</code>
       * @param value The opentypeFontData to set.
       * @return This builder for chaining.
       */
      public Builder setOpentypeFontData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        opentypeFontData_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes opentype_font_data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOpentypeFontData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        opentypeFontData_ = getDefaultInstance().getOpentypeFontData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CUIFontFilePB)
    }

    // @@protoc_insertion_point(class_scope:CUIFontFilePB)
    private static final kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB();
    }

    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CUIFontFilePB>
        PARSER = new com.google.protobuf.AbstractParser<CUIFontFilePB>() {
      @java.lang.Override
      public CUIFontFilePB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CUIFontFilePB> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CUIFontFilePB> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePB getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CUIFontFilePackagePBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CUIFontFilePackagePB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 package_version = 1;</code>
     * @return Whether the packageVersion field is set.
     */
    boolean hasPackageVersion();
    /**
     * <code>required uint32 package_version = 1;</code>
     * @return The packageVersion.
     */
    int getPackageVersion();

    /**
     * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
     */
    java.util.List<kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB> 
        getEncryptedFontFilesList();
    /**
     * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
     */
    kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB getEncryptedFontFiles(int index);
    /**
     * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
     */
    int getEncryptedFontFilesCount();
    /**
     * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
     */
    java.util.List<? extends kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePBOrBuilder> 
        getEncryptedFontFilesOrBuilderList();
    /**
     * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
     */
    kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePBOrBuilder getEncryptedFontFilesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code CUIFontFilePackagePB}
   */
  public static final class CUIFontFilePackagePB extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CUIFontFilePackagePB)
      CUIFontFilePackagePBOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 0,
        /* suffix= */ "",
        CUIFontFilePackagePB.class.getName());
    }
    // Use CUIFontFilePackagePB.newBuilder() to construct.
    private CUIFontFilePackagePB(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CUIFontFilePackagePB() {
      encryptedFontFiles_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kz.moltenhaze.proto.dota.UifontfileFormat.internal_static_CUIFontFilePackagePB_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kz.moltenhaze.proto.dota.UifontfileFormat.internal_static_CUIFontFilePackagePB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.class, kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.Builder.class);
    }

    public interface CUIEncryptedFontFilePBOrBuilder extends
        // @@protoc_insertion_point(interface_extends:CUIFontFilePackagePB.CUIEncryptedFontFilePB)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional bytes encrypted_contents = 1;</code>
       * @return Whether the encryptedContents field is set.
       */
      boolean hasEncryptedContents();
      /**
       * <code>optional bytes encrypted_contents = 1;</code>
       * @return The encryptedContents.
       */
      com.google.protobuf.ByteString getEncryptedContents();
    }
    /**
     * Protobuf type {@code CUIFontFilePackagePB.CUIEncryptedFontFilePB}
     */
    public static final class CUIEncryptedFontFilePB extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:CUIFontFilePackagePB.CUIEncryptedFontFilePB)
        CUIEncryptedFontFilePBOrBuilder {
    private static final long serialVersionUID = 0L;
      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 28,
          /* patch= */ 0,
          /* suffix= */ "",
          CUIEncryptedFontFilePB.class.getName());
      }
      // Use CUIEncryptedFontFilePB.newBuilder() to construct.
      private CUIEncryptedFontFilePB(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
      }
      private CUIEncryptedFontFilePB() {
        encryptedContents_ = com.google.protobuf.ByteString.EMPTY;
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kz.moltenhaze.proto.dota.UifontfileFormat.internal_static_CUIFontFilePackagePB_CUIEncryptedFontFilePB_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kz.moltenhaze.proto.dota.UifontfileFormat.internal_static_CUIFontFilePackagePB_CUIEncryptedFontFilePB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB.class, kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB.Builder.class);
      }

      private int bitField0_;
      public static final int ENCRYPTED_CONTENTS_FIELD_NUMBER = 1;
      private com.google.protobuf.ByteString encryptedContents_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes encrypted_contents = 1;</code>
       * @return Whether the encryptedContents field is set.
       */
      @java.lang.Override
      public boolean hasEncryptedContents() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bytes encrypted_contents = 1;</code>
       * @return The encryptedContents.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getEncryptedContents() {
        return encryptedContents_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          output.writeBytes(1, encryptedContents_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, encryptedContents_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB)) {
          return super.equals(obj);
        }
        kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB other = (kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB) obj;

        if (hasEncryptedContents() != other.hasEncryptedContents()) return false;
        if (hasEncryptedContents()) {
          if (!getEncryptedContents()
              .equals(other.getEncryptedContents())) return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasEncryptedContents()) {
          hash = (37 * hash) + ENCRYPTED_CONTENTS_FIELD_NUMBER;
          hash = (53 * hash) + getEncryptedContents().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input);
      }

      public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code CUIFontFilePackagePB.CUIEncryptedFontFilePB}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:CUIFontFilePackagePB.CUIEncryptedFontFilePB)
          kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePBOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return kz.moltenhaze.proto.dota.UifontfileFormat.internal_static_CUIFontFilePackagePB_CUIEncryptedFontFilePB_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return kz.moltenhaze.proto.dota.UifontfileFormat.internal_static_CUIFontFilePackagePB_CUIEncryptedFontFilePB_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB.class, kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB.Builder.class);
        }

        // Construct using kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          encryptedContents_ = com.google.protobuf.ByteString.EMPTY;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return kz.moltenhaze.proto.dota.UifontfileFormat.internal_static_CUIFontFilePackagePB_CUIEncryptedFontFilePB_descriptor;
        }

        @java.lang.Override
        public kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB getDefaultInstanceForType() {
          return kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB.getDefaultInstance();
        }

        @java.lang.Override
        public kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB build() {
          kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB buildPartial() {
          kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB result = new kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB result) {
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.encryptedContents_ = encryptedContents_;
            to_bitField0_ |= 0x00000001;
          }
          result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB) {
            return mergeFrom((kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB other) {
          if (other == kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB.getDefaultInstance()) return this;
          if (other.hasEncryptedContents()) {
            setEncryptedContents(other.getEncryptedContents());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  encryptedContents_ = input.readBytes();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private com.google.protobuf.ByteString encryptedContents_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes encrypted_contents = 1;</code>
         * @return Whether the encryptedContents field is set.
         */
        @java.lang.Override
        public boolean hasEncryptedContents() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>optional bytes encrypted_contents = 1;</code>
         * @return The encryptedContents.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getEncryptedContents() {
          return encryptedContents_;
        }
        /**
         * <code>optional bytes encrypted_contents = 1;</code>
         * @param value The encryptedContents to set.
         * @return This builder for chaining.
         */
        public Builder setEncryptedContents(com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          encryptedContents_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes encrypted_contents = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearEncryptedContents() {
          bitField0_ = (bitField0_ & ~0x00000001);
          encryptedContents_ = getDefaultInstance().getEncryptedContents();
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:CUIFontFilePackagePB.CUIEncryptedFontFilePB)
      }

      // @@protoc_insertion_point(class_scope:CUIFontFilePackagePB.CUIEncryptedFontFilePB)
      private static final kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB();
      }

      public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<CUIEncryptedFontFilePB>
          PARSER = new com.google.protobuf.AbstractParser<CUIEncryptedFontFilePB>() {
        @java.lang.Override
        public CUIEncryptedFontFilePB parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<CUIEncryptedFontFilePB> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<CUIEncryptedFontFilePB> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int PACKAGE_VERSION_FIELD_NUMBER = 1;
    private int packageVersion_ = 0;
    /**
     * <code>required uint32 package_version = 1;</code>
     * @return Whether the packageVersion field is set.
     */
    @java.lang.Override
    public boolean hasPackageVersion() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required uint32 package_version = 1;</code>
     * @return The packageVersion.
     */
    @java.lang.Override
    public int getPackageVersion() {
      return packageVersion_;
    }

    public static final int ENCRYPTED_FONT_FILES_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB> encryptedFontFiles_;
    /**
     * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
     */
    @java.lang.Override
    public java.util.List<kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB> getEncryptedFontFilesList() {
      return encryptedFontFiles_;
    }
    /**
     * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePBOrBuilder> 
        getEncryptedFontFilesOrBuilderList() {
      return encryptedFontFiles_;
    }
    /**
     * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
     */
    @java.lang.Override
    public int getEncryptedFontFilesCount() {
      return encryptedFontFiles_.size();
    }
    /**
     * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
     */
    @java.lang.Override
    public kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB getEncryptedFontFiles(int index) {
      return encryptedFontFiles_.get(index);
    }
    /**
     * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
     */
    @java.lang.Override
    public kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePBOrBuilder getEncryptedFontFilesOrBuilder(
        int index) {
      return encryptedFontFiles_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPackageVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, packageVersion_);
      }
      for (int i = 0; i < encryptedFontFiles_.size(); i++) {
        output.writeMessage(2, encryptedFontFiles_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, packageVersion_);
      }
      for (int i = 0; i < encryptedFontFiles_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, encryptedFontFiles_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB)) {
        return super.equals(obj);
      }
      kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB other = (kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB) obj;

      if (hasPackageVersion() != other.hasPackageVersion()) return false;
      if (hasPackageVersion()) {
        if (getPackageVersion()
            != other.getPackageVersion()) return false;
      }
      if (!getEncryptedFontFilesList()
          .equals(other.getEncryptedFontFilesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPackageVersion()) {
        hash = (37 * hash) + PACKAGE_VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getPackageVersion();
      }
      if (getEncryptedFontFilesCount() > 0) {
        hash = (37 * hash) + ENCRYPTED_FONT_FILES_FIELD_NUMBER;
        hash = (53 * hash) + getEncryptedFontFilesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CUIFontFilePackagePB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CUIFontFilePackagePB)
        kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kz.moltenhaze.proto.dota.UifontfileFormat.internal_static_CUIFontFilePackagePB_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kz.moltenhaze.proto.dota.UifontfileFormat.internal_static_CUIFontFilePackagePB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.class, kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.Builder.class);
      }

      // Construct using kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        packageVersion_ = 0;
        if (encryptedFontFilesBuilder_ == null) {
          encryptedFontFiles_ = java.util.Collections.emptyList();
        } else {
          encryptedFontFiles_ = null;
          encryptedFontFilesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kz.moltenhaze.proto.dota.UifontfileFormat.internal_static_CUIFontFilePackagePB_descriptor;
      }

      @java.lang.Override
      public kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB getDefaultInstanceForType() {
        return kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.getDefaultInstance();
      }

      @java.lang.Override
      public kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB build() {
        kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB buildPartial() {
        kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB result = new kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB result) {
        if (encryptedFontFilesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            encryptedFontFiles_ = java.util.Collections.unmodifiableList(encryptedFontFiles_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.encryptedFontFiles_ = encryptedFontFiles_;
        } else {
          result.encryptedFontFiles_ = encryptedFontFilesBuilder_.build();
        }
      }

      private void buildPartial0(kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.packageVersion_ = packageVersion_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB) {
          return mergeFrom((kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB other) {
        if (other == kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.getDefaultInstance()) return this;
        if (other.hasPackageVersion()) {
          setPackageVersion(other.getPackageVersion());
        }
        if (encryptedFontFilesBuilder_ == null) {
          if (!other.encryptedFontFiles_.isEmpty()) {
            if (encryptedFontFiles_.isEmpty()) {
              encryptedFontFiles_ = other.encryptedFontFiles_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureEncryptedFontFilesIsMutable();
              encryptedFontFiles_.addAll(other.encryptedFontFiles_);
            }
            onChanged();
          }
        } else {
          if (!other.encryptedFontFiles_.isEmpty()) {
            if (encryptedFontFilesBuilder_.isEmpty()) {
              encryptedFontFilesBuilder_.dispose();
              encryptedFontFilesBuilder_ = null;
              encryptedFontFiles_ = other.encryptedFontFiles_;
              bitField0_ = (bitField0_ & ~0x00000002);
              encryptedFontFilesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEncryptedFontFilesFieldBuilder() : null;
            } else {
              encryptedFontFilesBuilder_.addAllMessages(other.encryptedFontFiles_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasPackageVersion()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                packageVersion_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB m =
                    input.readMessage(
                        kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB.parser(),
                        extensionRegistry);
                if (encryptedFontFilesBuilder_ == null) {
                  ensureEncryptedFontFilesIsMutable();
                  encryptedFontFiles_.add(m);
                } else {
                  encryptedFontFilesBuilder_.addMessage(m);
                }
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int packageVersion_ ;
      /**
       * <code>required uint32 package_version = 1;</code>
       * @return Whether the packageVersion field is set.
       */
      @java.lang.Override
      public boolean hasPackageVersion() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required uint32 package_version = 1;</code>
       * @return The packageVersion.
       */
      @java.lang.Override
      public int getPackageVersion() {
        return packageVersion_;
      }
      /**
       * <code>required uint32 package_version = 1;</code>
       * @param value The packageVersion to set.
       * @return This builder for chaining.
       */
      public Builder setPackageVersion(int value) {

        packageVersion_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 package_version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPackageVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        packageVersion_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB> encryptedFontFiles_ =
        java.util.Collections.emptyList();
      private void ensureEncryptedFontFilesIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          encryptedFontFiles_ = new java.util.ArrayList<kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB>(encryptedFontFiles_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB, kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB.Builder, kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePBOrBuilder> encryptedFontFilesBuilder_;

      /**
       * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
       */
      public java.util.List<kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB> getEncryptedFontFilesList() {
        if (encryptedFontFilesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(encryptedFontFiles_);
        } else {
          return encryptedFontFilesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
       */
      public int getEncryptedFontFilesCount() {
        if (encryptedFontFilesBuilder_ == null) {
          return encryptedFontFiles_.size();
        } else {
          return encryptedFontFilesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
       */
      public kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB getEncryptedFontFiles(int index) {
        if (encryptedFontFilesBuilder_ == null) {
          return encryptedFontFiles_.get(index);
        } else {
          return encryptedFontFilesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
       */
      public Builder setEncryptedFontFiles(
          int index, kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB value) {
        if (encryptedFontFilesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEncryptedFontFilesIsMutable();
          encryptedFontFiles_.set(index, value);
          onChanged();
        } else {
          encryptedFontFilesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
       */
      public Builder setEncryptedFontFiles(
          int index, kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB.Builder builderForValue) {
        if (encryptedFontFilesBuilder_ == null) {
          ensureEncryptedFontFilesIsMutable();
          encryptedFontFiles_.set(index, builderForValue.build());
          onChanged();
        } else {
          encryptedFontFilesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
       */
      public Builder addEncryptedFontFiles(kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB value) {
        if (encryptedFontFilesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEncryptedFontFilesIsMutable();
          encryptedFontFiles_.add(value);
          onChanged();
        } else {
          encryptedFontFilesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
       */
      public Builder addEncryptedFontFiles(
          int index, kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB value) {
        if (encryptedFontFilesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEncryptedFontFilesIsMutable();
          encryptedFontFiles_.add(index, value);
          onChanged();
        } else {
          encryptedFontFilesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
       */
      public Builder addEncryptedFontFiles(
          kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB.Builder builderForValue) {
        if (encryptedFontFilesBuilder_ == null) {
          ensureEncryptedFontFilesIsMutable();
          encryptedFontFiles_.add(builderForValue.build());
          onChanged();
        } else {
          encryptedFontFilesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
       */
      public Builder addEncryptedFontFiles(
          int index, kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB.Builder builderForValue) {
        if (encryptedFontFilesBuilder_ == null) {
          ensureEncryptedFontFilesIsMutable();
          encryptedFontFiles_.add(index, builderForValue.build());
          onChanged();
        } else {
          encryptedFontFilesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
       */
      public Builder addAllEncryptedFontFiles(
          java.lang.Iterable<? extends kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB> values) {
        if (encryptedFontFilesBuilder_ == null) {
          ensureEncryptedFontFilesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, encryptedFontFiles_);
          onChanged();
        } else {
          encryptedFontFilesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
       */
      public Builder clearEncryptedFontFiles() {
        if (encryptedFontFilesBuilder_ == null) {
          encryptedFontFiles_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          encryptedFontFilesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
       */
      public Builder removeEncryptedFontFiles(int index) {
        if (encryptedFontFilesBuilder_ == null) {
          ensureEncryptedFontFilesIsMutable();
          encryptedFontFiles_.remove(index);
          onChanged();
        } else {
          encryptedFontFilesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
       */
      public kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB.Builder getEncryptedFontFilesBuilder(
          int index) {
        return getEncryptedFontFilesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
       */
      public kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePBOrBuilder getEncryptedFontFilesOrBuilder(
          int index) {
        if (encryptedFontFilesBuilder_ == null) {
          return encryptedFontFiles_.get(index);  } else {
          return encryptedFontFilesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
       */
      public java.util.List<? extends kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePBOrBuilder> 
           getEncryptedFontFilesOrBuilderList() {
        if (encryptedFontFilesBuilder_ != null) {
          return encryptedFontFilesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(encryptedFontFiles_);
        }
      }
      /**
       * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
       */
      public kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB.Builder addEncryptedFontFilesBuilder() {
        return getEncryptedFontFilesFieldBuilder().addBuilder(
            kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB.getDefaultInstance());
      }
      /**
       * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
       */
      public kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB.Builder addEncryptedFontFilesBuilder(
          int index) {
        return getEncryptedFontFilesFieldBuilder().addBuilder(
            index, kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB.getDefaultInstance());
      }
      /**
       * <code>repeated .CUIFontFilePackagePB.CUIEncryptedFontFilePB encrypted_font_files = 2;</code>
       */
      public java.util.List<kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB.Builder> 
           getEncryptedFontFilesBuilderList() {
        return getEncryptedFontFilesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB, kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB.Builder, kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePBOrBuilder> 
          getEncryptedFontFilesFieldBuilder() {
        if (encryptedFontFilesBuilder_ == null) {
          encryptedFontFilesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB, kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePB.Builder, kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB.CUIEncryptedFontFilePBOrBuilder>(
                  encryptedFontFiles_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          encryptedFontFiles_ = null;
        }
        return encryptedFontFilesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:CUIFontFilePackagePB)
    }

    // @@protoc_insertion_point(class_scope:CUIFontFilePackagePB)
    private static final kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB();
    }

    public static kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CUIFontFilePackagePB>
        PARSER = new com.google.protobuf.AbstractParser<CUIFontFilePackagePB>() {
      @java.lang.Override
      public CUIFontFilePackagePB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CUIFontFilePackagePB> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CUIFontFilePackagePB> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public kz.moltenhaze.proto.dota.UifontfileFormat.CUIFontFilePackagePB getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CUIFontFilePB_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CUIFontFilePB_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CUIFontFilePackagePB_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CUIFontFilePackagePB_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CUIFontFilePackagePB_CUIEncryptedFontFilePB_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CUIFontFilePackagePB_CUIEncryptedFontFilePB_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027uifontfile_format.proto\"C\n\rCUIFontFile" +
      "PB\022\026\n\016font_file_name\030\001 \001(\t\022\032\n\022opentype_f" +
      "ont_data\030\002 \001(\014\"\261\001\n\024CUIFontFilePackagePB\022" +
      "\027\n\017package_version\030\001 \002(\r\022J\n\024encrypted_fo" +
      "nt_files\030\002 \003(\0132,.CUIFontFilePackagePB.CU" +
      "IEncryptedFontFilePB\0324\n\026CUIEncryptedFont" +
      "FilePB\022\032\n\022encrypted_contents\030\001 \001(\014B\032\n\030kz" +
      ".moltenhaze.proto.dota"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CUIFontFilePB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CUIFontFilePB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CUIFontFilePB_descriptor,
        new java.lang.String[] { "FontFileName", "OpentypeFontData", });
    internal_static_CUIFontFilePackagePB_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CUIFontFilePackagePB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CUIFontFilePackagePB_descriptor,
        new java.lang.String[] { "PackageVersion", "EncryptedFontFiles", });
    internal_static_CUIFontFilePackagePB_CUIEncryptedFontFilePB_descriptor =
      internal_static_CUIFontFilePackagePB_descriptor.getNestedTypes().get(0);
    internal_static_CUIFontFilePackagePB_CUIEncryptedFontFilePB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CUIFontFilePackagePB_CUIEncryptedFontFilePB_descriptor,
        new java.lang.String[] { "EncryptedContents", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
