// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: valveextensions.proto
// Protobuf Java Version: 4.28.0

package kz.moltenhaze.proto.dota;

public final class Valveextensions {
  private Valveextensions() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "",
      Valveextensions.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(kz.moltenhaze.proto.dota.Valveextensions.valveMapField);
    registry.add(kz.moltenhaze.proto.dota.Valveextensions.valveMapKey);
    registry.add(kz.moltenhaze.proto.dota.Valveextensions.diffEncodeField);
    registry.add(kz.moltenhaze.proto.dota.Valveextensions.deltaIgnore);
    registry.add(kz.moltenhaze.proto.dota.Valveextensions.steammlMaxEntries);
    registry.add(kz.moltenhaze.proto.dota.Valveextensions.steammlIsTimestamp);
    registry.add(kz.moltenhaze.proto.dota.Valveextensions.steamlearnCount);
    registry.add(kz.moltenhaze.proto.dota.Valveextensions.schemaFriendlyName);
    registry.add(kz.moltenhaze.proto.dota.Valveextensions.schemaDescription);
    registry.add(kz.moltenhaze.proto.dota.Valveextensions.schemaSuppressEnumerator);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int VALVE_MAP_FIELD_FIELD_NUMBER = 61000;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> valveMapField = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int VALVE_MAP_KEY_FIELD_NUMBER = 61001;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> valveMapKey = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int DIFF_ENCODE_FIELD_FIELD_NUMBER = 61002;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Integer> diffEncodeField = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int DELTA_IGNORE_FIELD_NUMBER = 61003;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> deltaIgnore = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int STEAMML_MAX_ENTRIES_FIELD_NUMBER = 61004;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Integer> steammlMaxEntries = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int STEAMML_IS_TIMESTAMP_FIELD_NUMBER = 61005;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> steammlIsTimestamp = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int STEAMLEARN_COUNT_FIELD_NUMBER = 61006;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Integer> steamlearnCount = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int SCHEMA_FRIENDLY_NAME_FIELD_NUMBER = 1000;
  /**
   * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumValueOptions,
      java.lang.String> schemaFriendlyName = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int SCHEMA_DESCRIPTION_FIELD_NUMBER = 1001;
  /**
   * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumValueOptions,
      java.lang.String> schemaDescription = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int SCHEMA_SUPPRESS_ENUMERATOR_FIELD_NUMBER = 1002;
  /**
   * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumValueOptions,
      java.lang.Boolean> schemaSuppressEnumerator = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025valveextensions.proto\032 google/protobuf" +
      "/descriptor.proto:?\n\017valve_map_field\022\035.g" +
      "oogle.protobuf.FieldOptions\030\310\334\003 \001(\010:\005fal" +
      "se:=\n\rvalve_map_key\022\035.google.protobuf.Fi" +
      "eldOptions\030\311\334\003 \001(\010:\005false:=\n\021diff_encode" +
      "_field\022\035.google.protobuf.FieldOptions\030\312\334" +
      "\003 \001(\005:\0010:<\n\014delta_ignore\022\035.google.protob" +
      "uf.FieldOptions\030\313\334\003 \001(\010:\005false:?\n\023steamm" +
      "l_max_entries\022\035.google.protobuf.FieldOpt" +
      "ions\030\314\334\003 \001(\r:\0010:D\n\024steamml_is_timestamp\022" +
      "\035.google.protobuf.FieldOptions\030\315\334\003 \001(\010:\005" +
      "false:<\n\020steamlearn_count\022\035.google.proto" +
      "buf.FieldOptions\030\316\334\003 \001(\r:\0010:@\n\024schema_fr" +
      "iendly_name\022!.google.protobuf.EnumValueO" +
      "ptions\030\350\007 \001(\t:>\n\022schema_description\022!.go" +
      "ogle.protobuf.EnumValueOptions\030\351\007 \001(\t:F\n" +
      "\032schema_suppress_enumerator\022!.google.pro" +
      "tobuf.EnumValueOptions\030\352\007 \001(\010B\032\n\030kz.molt" +
      "enhaze.proto.dota"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    valveMapField.internalInit(descriptor.getExtensions().get(0));
    valveMapKey.internalInit(descriptor.getExtensions().get(1));
    diffEncodeField.internalInit(descriptor.getExtensions().get(2));
    deltaIgnore.internalInit(descriptor.getExtensions().get(3));
    steammlMaxEntries.internalInit(descriptor.getExtensions().get(4));
    steammlIsTimestamp.internalInit(descriptor.getExtensions().get(5));
    steamlearnCount.internalInit(descriptor.getExtensions().get(6));
    schemaFriendlyName.internalInit(descriptor.getExtensions().get(7));
    schemaDescription.internalInit(descriptor.getExtensions().get(8));
    schemaSuppressEnumerator.internalInit(descriptor.getExtensions().get(9));
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
